[project]
name = "idea"
version = "0.0.2"
description = "Shared IDEA Library"
authors = [
    {name = "Nationaal Dataportaal Wegverkeer Datakwaliteit (NDW)"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12"
]
readme = "README.md"
requires-python = ">=3.12.1"
dependencies = [
    "pandas==3.0.1",
    "singleton-decorator==1.0.0",
    "plotly==6.5.2",
]

[dependency-groups]
dev = [
    "pytest==9.0.2",
    "pytest-timeout==2.4.0",
    "pytest-cov==7.0.0",
    "parameterized==0.9.0",
    "pre-commit==4.5.1",
]

[tool.ruff]
src = ["idea"]
line-length = 100
target-version = "py312"

[tool.ruff.lint.pycodestyle]
max-doc-length = 100
max-line-length = 100

[tool.ruff.lint]
select = ["D",   # docstrings
    "E", # pycodestyle
    "F", # Pyflakes
    "UP",  # pyupgrade
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I",  # isort
    "W505"] # w505 checks for docstring comments lines to long
# makes docstrings not mandatory and less strict:
ignore = ["D417", "D202", "D205", "D101", "D102", "D103", "D100", "D401", "D104"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 100
